apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtc-app
      tier: backend
  template:
    metadata:
      labels:
        app: webrtc-app
        tier: backend
    spec:
      containers:
        - name: webrtc-backend
          image: tjtarun/webrtc-backend